export interface FormData {
  insuranceContract: {
    currentInsuranceCompany?: string
    unknownInsuranceCompany?: boolean
    isOneYearContract?: string
    expirationYear?: string
    expirationMonth?: string
    expirationDay?: string
    unknownExpirationDate?: boolean
    contractStartYear?: string
    contractStartMonth?: string
    contractStartDay?: string
    contractEndYear?: string
    contractEndMonth?: string
    contractEndDay?: string
    unknownContractPeriod?: boolean
    estimatedContractYears?: string
    switchTiming?: string
    previousContractSameCompany?: string
    previousContractOneYear?: string
    currentGrade?: string
    unknownCurrentGrade?: boolean
    estimatedGrade?: string
    accidentCoefficientPeriod?: string
    unknownAccidentCoefficient?: boolean
    accidentsThisPeriod?: string
    accidentType?: string
    cancellationYear?: string
    cancellationMonth?: string
    cancellationDay?: string
  }
  vehicleInfo: {
    registrationYear?: string
    registrationMonth?: string
    unknownRegistrationDate?: boolean
    estimatedYear?: string
    vehicleSearchMethod?: string
    hasDumpEquipment?: string
    hasAutoBrake?: string
    usagePurpose?: string
    expectedMileage?: string
    vehicleType?: string
    manufacturer?: string
    numberPlateType?: string
    truckType?: string
    truckWeight?: string
    modifiedCarType?: string
    electricCar?: string
  }
  personalInfo: {
    primaryUser?: string
    primaryUserForCashback?: string
    primaryUserBirthYear?: string
    primaryUserBirthMonth?: string
    primaryUserBirthDay?: string
    contractorBirthYear?: string
    contractorBirthMonth?: string
    contractorBirthDay?: string
    driverRestriction?: string
    ageCondition?: string
    certificateIssue?: string
  }
}
